### ISSUE TITLE
Wrong State shown for HmIP Shutter Actuators

### ISSUE THREAD

**Issue by captaindork** [ioBroker/ioBroker.hm-rpc#44] opened 2017-09-18 21:58 UTC
Hi,
HmIP Shutter Actuators show 99.5%, even if 100% up.
As there is also no pic for Shutter Actuators (HmIP-FROLL, BROLL, ...) I assume they are Not Suported yet? Can this be changed?

Thanks for a great Adapter!

**Comment by captaindork** [comment] 2017-10-29 17:55
Anything I could support with, to get this implemented?
For now I continuously change the LEVEL States of HmIP-FROLL to max 100% (instead of 100.499...) and in native I change max to 1 (instead of 1.005) this makes it working till next restart... which is quite annoying. Is there any way to have this working permanently?

**Comment by GermanBluefox** [comment] 2017-11-23 21:00
You can deliver the pictures from CCU web interface. 
How does the native information for this object look like?

**Comment by captaindork** [comment] 2017-11-23 21:13
Hi Bluefox,
Pic for HmIP-FROLL attached, also a Screenshot of the native tab which is working for me. Basically as mentioned above i just change Max from 1.005 to 1. Further in The General Tab I change Max to 100%. Both for the LEVEL Datapoint which exists in Channel 3,4,5 of FROLL. 
![48a70b17-51d4-45ab-9864-9eba03a0f20a](https://user-images.githubusercontent.com/28271030/33188602-89c8c574-d09b-11e7-99ac-7db6b14dbc10.png)
![89d9217e-ab9f-4b61-9e14-453bb5afe4f1](https://user-images.githubusercontent.com/28271030/33188603-89ea8650-d09b-11e7-90cb-3fc61c61c7bc.jpeg)

Then it is working for me.

**Comment by GermanBluefox** [comment] 2017-11-23 21:17
Actually you must see in log the entries like: Send it to developer.... 
Can you deliver such a lines? (but from log file, because in admin the lines are not full)

**Comment by captaindork** [comment] 2017-11-23 21:46
Hmm, actually in the log I can only see warnings about missing picture for HmIP-FROLL.
I understand which Lines you require, as I have seen this Developer lines in the past (maybe for other devices, I don‘t remember). However I cannot see them for the FROLL right now... any way to Force them to appear?

**Comment by captaindork** [comment] 2017-12-17 21:27
2017-12-17 22:16:47.355  - warn: hm-rpc.2 Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-FROLL.MAINTENANCE.1"
2017-12-17 22:16:47.356  - warn: hm-rpc.2 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"CONFIG_PENDING","TYPE":"BOOL","DEFAULT":false},"DUTY_CYCLE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"DUTY_CYCLE","TYPE":"BOOL","DEFAULT":false},"UNREACH":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":25,"ID":"UNREACH","TYPE":"BOOL","DEFAULT":false},"ERROR_OVERHEAT":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"ERROR_OVERHEAT","TYPE":"BOOL","DEFAULT":false},"RSSI_DEVICE":{"MIN":-128,"OPERATIONS":5,"MAX":127,"FLAGS":1,"ID":"RSSI_DEVICE","TYPE":"INTEGER","DEFAULT":0},"ERROR_UPDATE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"ERROR_UPDATE","TYPE":"BOOL","DEFAULT":false},"ACTUAL_TEMPERATURE":{"MIN":-3276.8,"OPERATIONS":5,"MAX":3276.7,"FLAGS":1,"ID":"ACTUAL_TEMPERATURE","TYPE":"FLOAT","DEFAULT":0},"OPERATING_VOLTAGE":{"MIN":0,"OPERATIONS":5,"MAX":25.2,"FLAGS":1,"ID":"OPERATING_VOLTAGE","TYPE":"FLOAT","DEFAULT":0},"RSSI_PEER":{"MIN":-128,"OPERATIONS":5,"MAX":127,"FLAGS":1,"ID":"RSSI_PEER","TYPE":"INTEGER","DEFAULT":0},"ERROR_OVERLOAD":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"ERROR_OVERLOAD","TYPE":"BOOL","DEFAULT":false},"ERROR_CODE":{"MIN":0,"OPERATIONS":5,"MAX":255,"FLAGS":9,"ID":"ERROR_CODE","TYPE":"INTEGER","DEFAULT":0},"UPDATE_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"UPDATE_PENDING","TYPE":"BOOL","DEFAULT":false}}}
2017-12-17 22:16:47.586  - warn: hm-rpc.2 Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-FROLL.KEY_TRANSCEIVER.1"
2017-12-17 22:16:47.587  - warn: hm-rpc.2 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"PRESS_SHORT":{"MIN":false,"OPERATIONS":4,"MAX":true,"FLAGS":1,"ID":"PRESS_SHORT","TYPE":"ACTION","DEFAULT":false,"CONTROL":"BUTTON_NO_FUNCTION.SHORT"},"PRESS_LONG":{"MIN":false,"OPERATIONS":4,"MAX":true,"FLAGS":1,"ID":"PRESS_LONG","TYPE":"ACTION","DEFAULT":false,"CONTROL":"BUTTON_NO_FUNCTION.LONG"}}}
2017-12-17 22:16:47.998  - warn: hm-rpc.2 Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-FROLL.SHUTTER_TRANSMITTER.1"
2017-12-17 22:16:48.000  - warn: hm-rpc.2 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"PROCESS":{"MIN":"STABLE","OPERATIONS":5,"MAX":"NOT_STABLE","FLAGS":1,"ID":"PROCESS","TYPE":"ENUM","DEFAULT":"STABLE","VALUE_LIST":["STABLE","NOT_STABLE"]},"LEVEL":{"MIN":0,"UNIT":"100%","OPERATIONS":5,"MAX":1.005,"FLAGS":1,"ID":"LEVEL","TYPE":"FLOAT","DEFAULT":0,"CONTROL":"SHUTTER_TRANSMITTER.LEVEL"},"SECTION":{"MIN":0,"OPERATIONS":5,"MAX":15,"FLAGS":1,"ID":"SECTION","TYPE":"INTEGER","DEFAULT":0}}}
2017-12-17 22:16:48.436  - warn: hm-rpc.2 Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-FROLL.SHUTTER_VIRTUAL_RECEIVER.1"
2017-12-17 22:16:48.440  - warn: hm-rpc.2 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"STOP":{"MIN":false,"OPERATIONS":2,"MAX":true,"FLAGS":1,"ID":"STOP","TYPE":"ACTION","DEFAULT":false,"CONTROL":"SHUTTER_VIRTUAL_RECEIVER.STOP"},"PROCESS":{"MIN":"STABLE","OPERATIONS":5,"MAX":"NOT_STABLE","FLAGS":1,"ID":"PROCESS","TYPE":"ENUM","DEFAULT":"STABLE","VALUE_LIST":["STABLE","NOT_STABLE"]},"LEVEL":{"MIN":0,"UNIT":"100%","OPERATIONS":7,"MAX":1.005,"FLAGS":1,"ID":"LEVEL","TYPE":"FLOAT","DEFAULT":0,"CONTROL":"SHUTTER_VIRTUAL_RECEIVER.LEVEL"},"SECTION":{"MIN":0,"OPERATIONS":5,"MAX":15,"FLAGS":1,"ID":"SECTION","TYPE":"INTEGER","DEFAULT":0}}}
2017-12-17 22:16:48.939  - warn: hm-rpc.2 Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-FROLL.BLIND_WEEK_PROFILE.1"
2017-12-17 22:16:48.940  - warn: hm-rpc.2 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"WEEK_PROGRAM_TARGET_CHANNEL_LOCK":{"MIN":"MANU_MODE","OPERATIONS":2,"MAX":"AUTO_MODE_WITHOUT_RESET","FLAGS":1,"ID":"WEEK_PROGRAM_TARGET_CHANNEL_LOCK","TYPE":"ENUM","DEFAULT":"MANU_MODE","VALUE_LIST":["MANU_MODE","AUTO_MODE_WITH_RESET","AUTO_MODE_WITHOUT_RESET"],"CONTROL":"WEEK_PROFILE.TARGET_CHANNEL_LOCK"},"WEEK_PROGRAM_TARGET_CHANNEL_LOCKS":{"MIN":0,"OPERATIONS":2,"MAX":16777215,"FLAGS":1,"ID":"WEEK_PROGRAM_TARGET_CHANNEL_LOCKS","TYPE":"INTEGER","DEFAULT":0,"CONTROL":"WEEK_PROFILE.TARGET_CHANNEL_LOCKS"},"WEEK_PROGRAM_CHANNEL_LOCKS":{"MIN":0,"OPERATIONS":5,"MAX":16777215,"FLAGS":1,"ID":"WEEK_PROGRAM_CHANNEL_LOCKS","TYPE":"INTEGER","DEFAULT":0,"CONTROL":"WEEK_PROFILE.CHANNEL_LOCKS"}}}

**Comment by captaindork** [comment] 2017-12-20 21:28
So i guess what happens is quite clear...
Homematic uses 0 for shut and 1 for open (0.5 for halfway, etc...)
However the state LEVEL is defined as min 0 max 1.005. Even if 1.005 is never being reached/deliviered from Homematic in normal operation.
ioBroker shows LEVEL as %. So state is open, homematic deliveres 1, ioBroker converts ist into % using the above min max values, and if 1.005 is max, then value 1 is 99.5% of it...
I now solved this permanently in my setup by multiplying/dividing the LEVEL states by 1.005 and using dummy-variables as helper... so from my side -> permanently fixed for my setup... even if a bit annoying.

**Comment by foxriver76** [comment] 2018-10-25 10:58
@GermanBluefox Is there are reason, that max for some values is 1.005 instead of 1?

**Comment by foxriver76** [comment] 2018-12-07 09:48
From my point of view we could just replace https://github.com/ioBroker/ioBroker.hm-rpc/blob/55d359345be4dd9bf9c4e71518a4f6eba32091b8/io-package.json#L12838 by a max value of 1.0 and the problem should be fixed. Unfortunately I have no device to test if there are any bad side effects.

**Comment by marvingrieger** [comment] 2019-01-04 21:08
I'm observing the same behavior ... shutters won't be opened / closed completely by setting the level to 100%. Quite annoying.

However, in the log I'm only getting messages like _No image for "HmIP-FROLL" found_ (same for _HmIP-SMI55_ and _HmIP-WGC_).

@GermanBluefox: The comment of @foxriver76 seems legitimate to me. Any chance you can apply the change? I can also do the testing - just need to know how.

**Comment by foxriver76** [comment] 2019-01-04 21:12
@marvingrieger I can implement/test it with you the next days, I just need to know that there is someone who can test it.

**Comment by foxriver76** [comment] 2019-01-04 22:21
Easiest way would be to edit your existing object of a hmip Froll device by going to tab objects and clicking on the edit button behind the level state and modifying the raw data. 

More complicated way:
You can still update the adapter from your fork. Just use Install from GitHub and use Custom URL. Then you have to do an upload of the adapter and I would recommend to delete the existing meta information of the effected device. Then just restart the adapter.

**Comment by captaindork** [comment] 2019-01-04 23:50
Basically the easy Option you mention is what I did and wanted to show as a working solution in my 3rd Post above with the Screenshot that shows the manipulation to max = 1.
What I exactly did was:
- under common: Change max to 100 (from “max“: 100.49999999999999)
- under native: Change MAX to 100 (from “MAX“: 100.49999999999999)
- Apply this for all LEVEL States of FROLL (channel 3/4/5/6)
- restart HmIP Instance of hm-rpc 

Which worked for me.

Sidenote: I am not doing this no longer, as there is a second issue: HmIP FROLL allows to write lets say 50 to the Level and it starts to Drive to this position Fine. However the value Instantly gets overwritten by 100 again. As soon as the FROLL really has reached Position 50, THEN the value is changed to 50. This makes the level of FROLL not really usable for further integrations like homekit-yahka. (As you move the slider or 50 and the slider will instantly pop to 100 again... it’s actually working and will also show 50 if you wait till the position is reached, but no good User experience...). Working with additional dummy states and some JavaScript will Fix this User experience. So as I needed this second tweak as well, I do the conversion of this Topic here as well in this Script). Not sure if this second Issue is a fix in the Adapter, or normal eQ-3 behavior... so fixing this one here would only be „part“ of a full fix for me...

**Comment by marvingrieger** [comment] 2019-01-05 10:30
Ok, manipulating the raw data worked as expected. In addition, I set up a separate ioBroker instance and installed the forked plugin. In this case, the values are correct in the first place.

<img width="398" alt="max_level" src="https://user-images.githubusercontent.com/1997765/50723325-6da6ac80-10dc-11e9-83e5-51006ed4593a.png">

Also, I didn't notice any strange behavior when opening and closing shutters. Creating a pull request now.

@captaindork I could also reproduce the behaviour you described in your sidenote. I simply logged the level value, the result can be seen here:

<img width="615" alt="level_behaviour" src="https://user-images.githubusercontent.com/1997765/50723362-d2fa9d80-10dc-11e9-8fb9-b04e81c1ef01.png">

Initially, the level is 0%. After setting it to 100%, it immediately jumps back to 0% and is only set to 100% after the shutter stopped. Guess we should open another issue. First step would be to have a closer look at the events created by the CCU to determine where the bug is located.

**Comment by foxriver76** [comment] 2019-01-05 10:35
The behavior is known to me from the shutters. But I expect that the API sends those values. You could enable debug logging to check. 

Von meinem iPhone gesendet

**Comment by marvingrieger** [comment] 2019-01-05 11:06
@foxriver76 One more thing: I found a lot _Send this info to developer_-messages in the log, like this one:

2019-01-04 22:51:30.441 - warn: hm-rpc.0 Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-WRC6.MAINTENANCE.1"
2019-01-04 22:51:30.441 - warn: hm-rpc.0 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"CONFIG_PENDING","TYPE":"BOOL","DEFAULT":false},"DUTY_CYCLE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"DUTY_CYCLE","TYPE":"BOOL","DEFAULT":false},"LOW_BAT":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"LOW_BAT","TYPE":"BOOL","DEFAULT":false},"INSTALL_TEST":{"MIN":false,"OPERATIONS":3,"MAX":true,"FLAGS":2,"ID":"INSTALL_TEST","TYPE":"BOOL","DEFAULT":false},"UNREACH":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":25,"ID":"UNREACH","TYPE":"BOOL","DEFAULT":false},"OPERATING_VOLTAGE_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"OVERFLOW","FLAGS":1,"ID":"OPERATING_VOLTAGE_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN","OVERFLOW"]},"RSSI_DEVICE":{"MIN":-128,"OPERATIONS":5,"MAX":127,"FLAGS":1,"ID":"RSSI_DEVICE","TYPE":"INTEGER","DEFAULT":0},"OPERATING_VOLTAGE":{"MIN":0,"OPERATIONS":5,"MAX":25.2,"FLAGS":1,"ID":"OPERATING_VOLTAGE","TYPE":"FLOAT","DEFAULT":0},"RSSI_PEER":{"MIN":-128,"OPERATIONS":5,"MAX":127,"FLAGS":1,"ID":"RSSI_PEER","TYPE":"INTEGER","DEFAULT":0},"UPDATE_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"UPDATE_PENDING","TYPE":"BOOL","DEFAULT":false}}}

Where should I post them? Or can I implement it by myself? Guess it just needs to be inserted into the _io-package.json_ file - is there a guide somewhere?

**Closed** 2019-01-05 11:09 UTC
Labels: refinement request

**Comment by foxriver76** [comment] 2019-01-05 11:12
You can post them in a separate issue or implement it in io-Package json. Have a look at recent ‚send this to dev‘ issues and how they have been closed.

**Comment by captaindork** [comment] 2019-01-05 11:13
Thanks a lot to all of you!

**Comment by foxriver76** [comment] 2019-01-09 21:45
FYI:
I now own a hmip froll by myself an had a closer look at meta of other devices  and hm ip froll metas. So I adjusted the meta info, so that max is 100, otherwise a restart of rega writes 1/currentShutterState in my data point and controls it. E. g. shutter is on 70 %, rega restart sets it to 0.7 %. I ve seen that many other meta information had this bug, where it says UNIT: 100 % and MAX: 1. IMHO when we have percent we should always scale from 0 to 100.

I also added the icon for HmIP-FROLL.

Fix is in https://github.com/ioBroker/ioBroker.hm-rpc/commit/4f819a457ecfe12d1c5bf28ee87d699867706921

**Comment by foxriver76** [comment] 2019-01-09 22:35
Do you also experience, that on a restart of hm-rega the levels are set to the value / 100? Also instead of 30 % it writes 0.3 % in the state.

**Comment by captaindork** [comment] 2019-01-09 22:45
Definitely on a restart of hm-rpc or rega it is set to 1% if it was 100 before... this is quite annoying as you just work a bit on iobroker and suddenly the shutters are all down :)... I personally thought setting „default“ in RAW to 100 would fix this, but it doesn‘t. So I would say yes confirmed. While honestly my feeling is: it’s not happening with every normal restart -> it’s only if you delete the state and let it freshly create by the adapters...so rather when doing a „full refresh“...

**Comment by captaindork** [comment] 2019-01-09 22:48
By the way... the 99.5 to 100% topic is fixed now with your 1.9.1. it was not fixed for me when we closed this git issue with 1.9.0. so -> Thanks. I removed the conversion x1.005 from my helper scripts...

**Comment by foxriver76** [comment] 2019-01-09 23:07
> By the way... the 99.5 to 100% topic is fixed now with your 1.9.1. it was not fixed for me when we closed this git issue with 1.9.0. so -> Thanks. I removed the conversion x1.005 from my helper scripts and it works flawlessly!

This can have several reasons, e. g. after a GitHub update, an upload of the adapter is necessary. 
I installed the shutter actor today and until now I am experiencing this issue on every restart of hm-rega (not hm-rpc) and the wrong state is also written by rega and not hm-rpc. So guess I have to check hm-rega code.

**Comment by foxriver76** [comment] 2019-01-10 00:33
Fixed the issue in https://github.com/ioBroker/ioBroker.hm-rega/commit/8cf025239437204d435f34417061818bce25e444
