### ISSUE TITLE
	xmlrpc -> setValue: no dpType for hm-rpc.0.IEQ0041079.1.STATE!

### ISSUE THREAD

**Issue by BS-GIFHUB** [ioBroker/ioBroker.hm-rpc#410] opened 2021-11-19 20:31 UTC
HI,

the interface to homematic doesn't work anymore. The Blockly program in Java script is

on({id: 'javascript.0.Aussenbeleuchtung.switch', change: "ne"}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("javascript.0.Aussenbeleuchtung.switch").val == true) {
    setState("zwave2.0.Node_002.Binary_Switch.targetValue_003"/*Target value (Endpoint 3)*/, true);
    setState("zwave2.0.Node_003.Binary_Switch.targetValue_003"/*Target value (Endpoint 3)*/, true);
    setState("shelly.0.SHSW-1#F398A6#1.Relay0.Switch"/*Switch*/, true);
    setState("hm-rpc.0.IEQ0041079.1.STATE"/*Schalter Außenbeleuchtung:1.STATE*/, true);
    setState("shelly.0.SHSW-1#F41BAE#1.Relay0.Switch"/*Switch*/, true);
  } else {
    setState("zwave2.0.Node_002.Binary_Switch.targetValue_003"/*Target value (Endpoint 3)*/, false);
    setState("zwave2.0.Node_003.Binary_Switch.targetValue_003"/*Target value (Endpoint 3)*/, false);
    setState("shelly.0.SHSW-1#F398A6#1.Relay0.Switch"/*Switch*/, false);
    setState("hm-rpc.0.IEQ0041079.1.STATE"/*Schalter Außenbeleuchtung:1.STATE*/, false);
    setState("shelly.0.SHSW-1#F41BAE#1.Relay0.Switch"/*Switch*/, false);
  }

It works, but meanwhile after updates I got the no dbType error also on other Homematic devices like CuxD states.

Thanks for any help.

Benrhard

**Comment by foxriver76** [comment] 2021-11-19 23:02
Then due to some reason `hm-rpc.meta.roles` has been deleted, two options. Upgrade to latest or upload adapter via `iob u hm-rpc`

**Comment by foxriver76** [comment] 2021-11-19 23:02
and duplicate of #407  btw

**Closed by foxriver76** 2021-11-19 23:02 UTC
