### ISSUE TITLE
Verify Compact mode for your adapter

### ISSUE THREAD

**Issue by ioBrokerChecker** [ioBroker/ioBroker.hm-rpc#202] opened 2019-10-21 10:04 UTC
We have detected that your adapter supports the compact mode. Please use the latest js-controller 2.0 and verify that everything works.

Some more information what is important to check can be found at https://github.com/ioBroker/ioBroker.js-controller/issues/512 

On questions please answer to the linked issue. Please close this issue after your test and add the version number that you have tested please as a comment.

Thank you for your support.

**Comment by jpawlowski** [comment] 2019-10-26 13:40
It seems that enabling compact mode will mix-up the objects, e.g. they will no longer appear under the node they usually should but rather appear on a different instance's node.

**Comment by foxriver76** [comment] 2019-10-26 13:51
Exact example or Screenshot could might be useful.

**Comment by jpawlowski** [comment] 2019-10-27 09:07
Way to reproduce:

1. Clean container install using André's Docker image (current beta).
2. Set upgrade repository to `latest`
3. Upgrade js-controller and default adapters to latest version.
4. Enable compact mode: `iob compact enable`
5. Setup hm-rega.0 with hm-rpc.0 (HmIP) and hm-rpc.1 (HmClassic)
6. Enable compact mode for instances: `iob compact hm-rega.0 enable 1; iob compact hm-rpc.0 enable 1; iob compact hm-rpc.1 enable 1`
7. Use dedicated compact groups for RPC: `iob compact hm-rpc.0 group 2; iob compact hm-rega.0 group 2;`

As a result, HmIP devices will show up in both instance nodes, hm-rcp.0 (where they belong) and hm-rcp.1 (which shouldn't be):

![image](https://user-images.githubusercontent.com/75446/67632257-9c775480-f8a1-11e9-92a3-6b13259c28f6.png)

**Comment by foxriver76** [comment] 2019-10-27 11:17
Confirmed, there is a strange behaviour. For me it ended up having only rfd devices in both namespaces (rfd is my hm-rpc.0)

@Apollon77 is it already tested, having 2 instances of the same adapter in the same comapct group?

**Comment by Apollon77** [comment] 2019-10-27 16:22
Technically this should be completely irrelevant if compact mode or not and such. 

For compact mode there is a slight chance that „global“ working libraries (so libs that do not create object instances and store data on such a level) mix up. Maybe it is something like this?

On the other hand vm2 is used where code runs in. I have no idea how separated requires are there then. 

I can also have a look at the hm-rpc Code later

Ingo

**Comment by foxriver76** [comment] 2019-11-02 01:06
@Apollon77 As mentioned in Telegram, when the whole code is in `startAdapter` function it works well. So a compact group seems to share global variables. Which is not only a problem when using the same adapter multiple times in a group, but also when two different adapters use same names for some global variables.

**Comment by Apollon77** [comment] 2019-11-02 06:14
Just variable names should not be the reason ... but great to know

**Comment by foxriver76** [comment] 2019-11-08 16:43
Seems fixed with js-controller 2.0.40

**Closed by foxriver76** 2019-11-08 16:43 UTC
