### ISSUE TITLE
hm-rpc.2.CENTRAL.PONG

### ISSUE THREAD

**Issue by GROSSMAS** [ioBroker/ioBroker.hm-rpc#310] opened 2021-02-19 10:20 UTC
Nach Update auf js-controller 3.2 stable folgenden Fehler:

`
hm-rpc.3 | 2021-02-19 11:15:26.947 | warn | (23456) State "hm-rpc.3.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions
hm-rpc.2 | 2021-02-19 11:15:24.842 | warn | (23441) State "hm-rpc.2.CENTRAL.PONG" has no existing object, this might lead to an error in future versions
hm-rpc.1 | 2021-02-19 11:15:19.979 | warn | (23414) State "hm-rpc.1.CENTRAL.PONG" has no existing object, this might lead to an error in future versions
`
Adapter: HomeMatic RPC 1.14.24

**Comment by foxriver76** [comment] 2021-02-19 10:21
..

**Comment by foxriver76** [comment] 2021-02-19 10:21
duplicate of #309, #297 and already fixed

**Closed by foxriver76** 2021-02-19 10:21 UTC

**Comment by GROSSMAS** [comment] 2021-02-19 10:30
Sorry

**Comment by GROSSMAS** [comment] 2021-02-19 10:30
In welcher Version ist es Damm gefixt?

**Comment by foxriver76** [comment] 2021-02-19 11:05
Kein Ding, nur keine 5 Min vorher das gleiche Verhalten im Issue gehabt :wink:
