### ISSUE TITLE
Heating Groups

### ISSUE THREAD

**Issue by sissiwup** [ioBroker/ioBroker.hm-rpc#148] opened 2019-01-26 11:08 UTC
common name not set.
The name of the group is not set in common -> name

Empty field make problems. When not avaible, take the SHort Name of the Device,
for example INT000001

**Comment by foxriver76** [comment] 2019-01-26 11:34
@sissiwup have you also configured hm-rega for your virtual-devices instance?
@Holuba due to the fact, that you are the only dev I know using the virtual devices, maybe you can say something to this. Normally the ID is taken into account for the name and afterwards renamed by hm-rega.

**Comment by foxriver76** [comment] 2019-01-26 11:54
And @sissiwup is your Rega Adapter up to date? There was an issue from version 1.2.3 to 1.2.6 I think.

**Comment by foxriver76** [comment] 2019-01-26 13:50
Can reproduce it with a dummy heating group.

**Comment by foxriver76** [comment] 2019-01-26 13:59
Is fixed in hm-rega 2.2.0

**Closed by foxriver76** 2019-01-26 13:59 UTC
Labels: bug

**Comment by Baenker** [comment] 2019-01-27 18:02
With Version 1.92 (and 2.1.8 rega) the comman name is set correct. No Problems in my setup
