### ISSUE TITLE
xmlrpc -> setValue: no dpType for hm-rpc.1.XXX.2.STATE!

### ISSUE THREAD

**Issue by fajito-x** [ioBroker/ioBroker.hm-rpc#407] opened 2021-11-04 10:36 UTC
**Describe the bug**
I use the yahka adapter to controll a HmIP-FSM via Homekit. However, starting with version hm-rpc v1.14.42 when trying to change the state of the HmIP-FSM I get the following error:
`xmlrpc -> setValue: no dpType for hm-rpc.1.XXX.2.STATE!`

The same error occurrs with versions 1.14.43, 1.14.44, 1.14.45
When rolling back to 1.14.41 everthing works as expected. The state gets correctly set an no error occurrs.

**To Reproduce**
1. Update hm-rpc to version 1.14.42, 43, 44 or 45
2. Try to change the hm-rpc.1.XXX.2.STATE of a HmIP-FSM (other devices might be also affected) 
3. See error in log

**Expected behavior**
No error should occurr and the state of the HmIP device shall be changed correctly.

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.31
 - JS-Controller version: 3.3.18
 - Node version: 12.22.7
 - Operating system: Raspbian GNU/Linux 10
 - CCU model: piVCCU3
 - CCU firmware: 3.59.6

**Comment by foxriver76** [comment] 2021-11-04 11:05
changes of 1.14.42 are all made by @GermanBluefox, however, by looking at the commits, I cannot see anything which should cause this.

However, you could post the raw datapoint and debug log from adapter start until the error occurs.

**Comment by gswdn** [comment] 2021-11-14 15:49
I have the same issue. Yesterday, some lights stopped working. Did the usual update yesterday morning, but can't remember, if I updated hm-rpc. I don't find anything in my logs from yesterday morning. When was 1.14.45 released into production repro?

The same error message appears in my log files every time I try to change the state of one of the lights. Only HM.IP components are affected. Classic HM components still work. There's nothing else. Just that one line in the log.

I was on 1.14.45. Downgraded to 1.14.41 and lights started working again. 

Is this what you mean by "raw data point"?

`{
  "type": "state",
  "common": {
    "name": "xxxxx.STATE",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": true
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 7,
    "MAX": true,
    "FLAGS": 1,
    "ID": "STATE",
    "TYPE": "BOOL",
    "DEFAULT": false,
    "CONTROL": "SWITCH.STATE"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1636901694234,
  "_id": "hm-rpc.1.xxxxx.4.STATE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by foxriver76** [comment] 2021-11-14 16:04
Are other dps affected or only those ending in `STATE` and are all of them are of type `SWITCH.STATE` in native? Maybe it has something to do with the type

**Comment by gswdn** [comment] 2021-11-14 16:17
That's even more wired. I have just upgraded to 1.14.45 again to test other data point types. Guess what: the originally affected ones now work again. And: no line in the logs.
Sorry, I'm not able to replicate the issue currently.
I observe and test, once this happens again. If it happens again. Strange.
Or do you have any other suggestion on how to track this down?

**Comment by csicom** [comment] 2021-11-14 19:10
I have the same problem with Homematic IP devices. I chanched name of the device in CCU. I think, that is the problem.
The name is displayed correctly in channel 0 in IOBroker but the id of the device is displayed in channel 1.

**Comment by foxriver76** [comment] 2021-11-14 19:13
not sure if a name change can lead to this behavior but we can test it. But in all cases after adapter restart it should work again? Can you try if you can reproduce this issue by renaming a device in the CCU?

**Comment by mesche** [comment] 2021-11-16 14:57
Hi,
unfortunately I am not sure, but maybe it could be the same problem as mine. 

I had published a post about this:
[Steuerung von HM-Komponenten via XML-API nicht mehr möglich](https://forum.iobroker.net/topic/48342/steuerung-von-hm-komponenten-via-xml-api-nicht-mehr-m%C3%B6glich) (Sorry for all non german speaking)

Error occurred:  1.14.45   ---> downgrade to 1.14.42 --> no error --> update to 1.14.45  ---> no error at the moment

**Comment by foxriver76** [comment] 2021-11-16 15:02
I need a reproduceable example, else I cannot help also downgrade versions differ and then it works also with newest version etc.. seems all like coincidence and that the error is not dependent on the latest version. I guess it occurs if some specific conditions are met

**Comment by fajito-x** [comment] 2021-11-17 19:57
Today I upgraded to hm-rega@3.0.32 and to yahka@0.13.1 as new latest versions and after that also upgraded to hm-rpc@1.14.45 again.
Now everything works as expected, so I would consider this issue report closed.

**Comment by fajito-x** [comment] 2021-11-18 20:18
I am afraid I have to reopen the issue. Today, after a restart of the hm-rpc adapter it's not working again.
After a restart of the adapter there is following error in the log:
`Could not get state view on start: Cannot read property 'CONFIG_PENDING' of undefined`

**Comment by fajito-x** [comment] 2021-11-18 20:27
This forum thread seems to report the same issue: [Kommunikation CCU/Rasberrymatic -> Iobroker Problem](https://forum.iobroker.net/topic/48317/kommunikation-ccu-rasberrymatic-iobroker-problem)

**Comment by foxriver76** [comment] 2021-11-18 20:31
Can you try 1.14.47, it seems like `metaRoles` is undefined here https://github.com/ioBroker/ioBroker.hm-rpc/blob/0f929b630e0310382a388f56625369e6e781f390/main.js#L811

**Comment by fajito-x** [comment] 2021-11-18 20:38
I tried 1.14.48 with the same errors described above and then downgraded to 1.14.47. Unfortunately, with this version the adapter does not start at all. Following error message:
`No meta values retrived, check your installation. "hm-rpc.meta.roles" may be corrupted.`

**Comment by foxriver76** [comment] 2021-11-18 20:40
yes, thats fine. so does the `hm-rpc.meta.roles` object exist?

**Comment by foxriver76** [comment] 2021-11-18 20:41
but yes theres a versioning problem, 1.14.47 needs to be higher 1.14.49

**Comment by fajito-x** [comment] 2021-11-18 20:43
> yes, thats fine. so does the hm-rpc.meta.roles object exist?
No, there is no object `hm-rpc.meta.roles`

**Comment by foxriver76** [comment] 2021-11-18 20:47
Then, that's the problem ;-)

Please show output of `iob o get hm-rpc.meta.roles` and **after that** `iob u hm-rpc` then again check the output of `iob o get hm-rpc.meta.roles`

**Comment by fajito-x** [comment] 2021-11-18 20:56
That solves the problem!
Can you make sure that a potentially corrupted data can be automatically remedied for other installations?

**Comment by foxriver76** [comment] 2021-11-18 21:17
My propose is to not provide it as object anymore because it will be read at start and then kept in RAM for whole run, thus no advantage of an object.

**Closed** 2021-11-18 21:20 UTC
Labels: refinement request
